### ISSUE TITLE
Missing org symbol "org-show-all"

### ISSUE THREAD

**Issue by Trevoke** [purcell/setup-emacs#10]
Hello, I'm trying to use your action to nicely set up a build for an emacs package, but I'm running into the following issue:

https://github.com/Trevoke/org-gtd.el/runs/1008243337?check_suite_focus=true

```
Traceback (most recent call last):
  (org-capture nil "i")
  (error "Capture template `%s': %s" "i" "Symbol’s function definition is void: org-show-all")
  (signal error ("Capture template ‘i’: Symbol’s function definition is void: org-show-all"))
error: (error "Capture template ‘i’: Symbol’s function definition is void: org-show-all")
```

I have no idea how to fix this, so ... I could use a little bit of help.

What I have done:

1. added `org` as a test dependency in `eldev`
2. required `org` explicitly at the top of my currently lone test file
3. cried

And nothing has worked. I'm fairly certain this isn't an issue with your action, but I'm also fairly certain I don't know where else to ask :)

**Comment by Trevoke** [comment]
Addendum - I have managed to confirm this is just an issue with the org-mode version, so I _think_ the correct place to ask is eldev. Sorry for the trouble :)

**Comment by purcell** [comment]
Ah, thanks for tracking that down.
