### ISSUE TITLE
CI in Windows

### ISSUE THREAD

**Issue by jcs090218** [purcell/setup-emacs#11]
Sorry that I made a mistake by opened an issue here https://github.com/purcell/nix-emacs-ci/issues/27. I was confused by the name of the two projects. 😖 

I was asking if it is possible to test Emacs on Windows? But I think you already answer the question? (Just want to make sure!) Thanks!

**Comment by purcell** [comment]
Correct, this Action does not support Windows and it is fundamentally unable to.

**Comment by jcs090218** [comment]
Thanks for answering! I appreciated! :)
