### ISSUE TITLE
GitHub is depreciating set-env & add-path commands

### ISSUE THREAD

**Issue by rnkn** [purcell/setup-emacs#15]
Hello,

I'm sure you're already aware of this via your own use, but apparently [GitHub is depreciating](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/) `set-env` and `add-path` commands, which will now [trigger warnings in builds](https://github.com/rnkn/binder/runs/1251707239?check_suite_focus=true#step:2:32).

**Comment by purcell** [comment]
Thanks for the heads-up -- I wasn't aware of this.

**Comment by purcell** [comment]
Fixed by #16

**Comment by rnkn** [comment]
Wow this was not a trivial fix. Thanks :)

**Comment by purcell** [comment]
Yeah, took a bit of figuring out.

**Comment by sinic** [comment]
Would it be possible to tag a new version that contains the fixes for this issue? Otherwise users are enticed by [the GitHub marketplace](https://github.com/marketplace/actions/set-up-emacs) to use the newest version (`v2.0` at the time of writing), which will soon stop working.

**Comment by purcell** [comment]
Yes, done, thanks.
