### ISSUE TITLE
v3.0 has not been published on the marketplace

### ISSUE THREAD

**Issue by taiju** [purcell/setup-emacs#17]
To publish to the marketplace, it seems that tagging is not enough, you need to create a release.
https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/publishing-actions-in-github-marketplace#publishing-an-action

I'm not troubled because I can use v3.0, but new users will mistakenly think #15 is unresolved because v3.0 does not exist in the marketplace.

**Comment by purcell** [comment]
Thanks, done.
