### ISSUE TITLE
Command fail, install-nix.sh

### ISSUE THREAD

**Issue by jcs090218** [purcell/setup-emacs#19]
I am getting this error on Emacs 27.1. 😕 

```
Command failed: /home/runner/work/_actions/purcell/setup-emacs/master/dist/install-nix.sh emacs-27-1
```

I think the bug is cause by nix?

* The full page link is here, https://github.com/jcs090218/jcs-emacs/runs/1583536271

**Comment by akirak** [comment]
I encounter the same error on my local machine too. It looks like an issue with cachix.

**Comment by purcell** [comment]
Yes, cachix is down.

**Comment by akirak** [comment]
@jcs090218 The issue seems to be fixed now.

**Comment by jcs090218** [comment]
Thanks! Close this now!
