### ISSUE TITLE
emacs: standard input is not a tty

### ISSUE THREAD

**Issue by tomdl89** [purcell/setup-emacs#21]
Hello 👋 I've tried moving evil from travis to github actions, and I've made _some_ progress, but some tests are now skipping, and the emacs 24.5 runner outright fails. Initially I just tried using this action and the same command:
```
script -eqc 'make test' > /dev/null
```
which runs
```
emacs -nw -Q -L . -l lib -l evil-tests.el --eval "(evil-tests-initialize)"
```
but this (which always worked fine on travis) now failed on github actions, with the error:
```
emacs: standard input is not a tty
```
My hacky solution is to add the `--batch` option to that command, which results in some tests being skipped, and only the emacs 24.5 runner outright failing. I have no idea why 24.5 is the only one failing - I assume emacs changed the way it handled `--batch` in later releases?

I thought `script -eqc...` would fool emacs into thinking it had a tty standard input, but when running on github actions, it seems it still knows. Is there some way around this? Thanks in advance!

**Comment by purcell** [comment]
Hmmm, not actually sure about that, sorry. For some reason this is ring a bell in my mind though... I feel like I've heard something about this behaviour before.

**Comment by tomdl89** [comment]
No problem - it's just good to know I'm not overlooking something obvious! If anything comes to mind please drop me a message.
