### ISSUE TITLE
Installation on macOS fails since recently

### ISSUE THREAD

**Issue by doublep** [purcell/setup-emacs#24]
Since recently (used to work with the same .yml on October 27th), [installation with the action on macOS fails](https://github.com/doublep/eldev/runs/4096145439?check_suite_focus=true), with an error that tells me nothing. From the same run, [installation on Linux](https://github.com/doublep/eldev/runs/4096144754?check_suite_focus=true) works fine: the job gets cancelled later, when Emacs is already successfully installed. The [used .yml file](https://github.com/doublep/eldev/blob/master/.github/workflows/test.yml) contains nothing special for this step, as far as I can see.

It appears that Nix fails with a cryptic error. Can you make any sense out of it? Thank you.

**Comment by JAremko** [comment]
https://github.com/syl20bnr/spacemacs/runs/4109064716?check_suite_focus=true yeah it's failing for quire a while now.

**Comment by purcell** [comment]
Fixed by #26, thanks for letting me know

**Comment by doublep** [comment]
Yes, works now. Thank you.
