### ISSUE TITLE
Intermittent 504s downloading from github.com/NixOS/nixpkgs

### ISSUE THREAD

**Issue by jinnovation** [purcell/setup-emacs#27]
I use setup-emacs for CI in [kubernetes-el](github.com/kubernetes-el/kubernetes-el).

In the last couple of days I've noticed intermittent failures in CI steps using `purcell/setup-emacs@master`. These appear to consistently stem from 504s in downloading from NixOS/nixpkgs:
```
warning: error: unable to download 'https://github.com/NixOS/nixpkgs/archive/48acffcc81a5acd315c0b719d1f624223efca99d.tar.gz': HTTP error 504
```

See [this particular test run](https://github.com/kubernetes-el/kubernetes-el/runs/6966392656) for an example.

Anything in either setup-emacs or nix-emacs-ci that needs to be updated?

Thanks as always 😎

**Comment by iwahbe** [comment]
I'm getting the same thing.

[Here](https://github.com/iwahbe/jsonian/runs/6996576055?check_suite_focus=true) is another example if it helps. Let me know if there is anything I can do to help/fix it.

**Comment by purcell** [comment]
I've seen sporadic issues in CI downloading that URL, but there's nothing particularly special about it. I'll update it to a newer revision in case Github's tarball cache is messed up, but I'm wondering if it's some sort of rate-limiting thing going on, or transient errors on github's side.

**Comment by purcell** [comment]
Update done, maybe that will be more reliable, but that will be more a matter of luck than having fixed a well-understood issue.

Thanks so much for letting me know that you've been having issues, it's hard for me to have broad visibility of that.

**Comment by jinnovation** [comment]
Thanks for following up @purcell ✌️
