### ISSUE TITLE
Update action to Node 16

### ISSUE THREAD

**Issue by smoeding** [purcell/setup-emacs#29]
I'm using `purcell/setup-emacs@master` in a Github workflow and lately I'm seeing warnings about Node 12 deprecation.
It seems all actions need to update to Node 16:
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

Could you update your code accordingly? Thanks!

**Comment by purcell** [comment]
Fixed by #30, I believe.
