### ISSUE TITLE
Macos-capable?

### ISSUE THREAD

**Issue by dickmao** [purcell/setup-emacs#3]
Hi, installNix.ts yields the following with matrix.os set to `macos-latest`:

```
  performing a single-user installation of Nix...
  directory /nix does not exist; creating it by running 'mkdi ... using sudo
  mkdir: /nix: Read-only file system
  /var/...: please manually run 'mkdir -m 0755 /nix ... chown runner...' as root
  ##[error]Action failed with error: Error: The process 'sh' failed with exit code 1
  ##[error]The process 'sh' failed with exit code 1
  ##[error]Node run failed with exit code 1
```
As a linux user, I don't know best practices to `mkdir` in toplevel `/` on macos.

**Comment by purcell** [comment]
In theory, yes, this should all work on MacOS too. Unfortunately, Catalina has broken the upstream Nix installation process: see https://github.com/purcell/nix-emacs-ci/issues/15 for more info and my plans for this.

**Comment by dickmao** [comment]
Okay, thank you.

**Comment by purcell** [comment]
I'm having a little look at this now to see if I can work around it.

**Comment by purcell** [comment]
I think that's fixed now.
