### ISSUE TITLE
Recent failure, macOS only

### ISSUE THREAD

**Issue by doublep** [purcell/setup-emacs#37]
Hello. Apparently the action got broken on macOS, presumably because GitHub upgraded from 12.6.5 to 12.6.6 or maybe made some configuration tweaks.

[Example of a failed installation](https://github.com/doublep/eldev/actions/runs/5326471086/jobs/9648988096) (I tried rerunning it, doesn't help). [Example of a working setup on macOS](https://github.com/doublep/eldev/actions/runs/5258885386/jobs/9503709718) a week ago, where GitHub reported 12.6.5.

I disabled testing on macOS for now. The action works fine on Linux.

**Comment by jcs090218** [comment]
In case if anyone care, this is how your fix it: https://github.com/jcs090218/setup-emacs/commit/a3f951fe9c208bf540fbd047736d09e158b021bf.
