### ISSUE TITLE
Emacs installation failed in 27-2

### ISSUE THREAD

**Issue by jcs090218** [purcell/setup-emacs#48]
I'm recently getting this error. 🤔 Any idea?

```
copying path '/nix/store/63wn3078wdbrrax7vbcamzffaabmsvdl-source' from 'https://cache.nixos.org/'...
  error: flake 'github:purcell/nix-emacs-ci' does not provide attribute 'packages.aarch64-darwin.emacs-27-2', 'legacyPackages.aarch64-darwin.emacs-27-2' or 'emacs-27-2'
         Did you mean one of emacs-28-2, emacs-29-2, emacs-28-1, emacs-29-1 or emacs-29-3?
```

**Comment by akirak** [comment]
@jcs090218 See https://github.com/purcell/nix-emacs-ci/pull/268:

> Older Emacsen cannot be built on ARM MacOS.

I'm afraid the older Emacs versions are no longer available for `macos-latest` but for `macos-11`? This is due to the update of GitHub Actions and does not related to `setup-emacs`.

**Comment by jcs090218** [comment]
Oh okay. Thank you for pointing me to the thread! Closing this issue now.

**Comment by purcell** [comment]
Additionally, macos-11 will be retired in June, so I don't know what this looks like for longer-term. I imagine the interest in running/testing Emacs on Intel Macs is rapidly disappearing anyway, so most GitHub authors should be content to just use Linux + ARM MacOS in theri GitHub Actions CI.
