### ISSUE TITLE
Any idea how to build Emacs dynamic module?

### ISSUE THREAD

**Issue by xuchunyang** [purcell/setup-emacs#6]
I'm trying to test a dynamic module with github action, but it fails

> strptime-core.c:1:10: fatal error: emacs-module.h: No such file or directory
>  #include <emacs-module.h>

only `emacs-module.h` is required to build the Emacs dynamic module, and Emacs 27.1+ builds with dynamic module by default (unless you pass `--without-modules`), thus the snapshot emacs should have already installed `emacs-module.h`, but `cc` couldn't find it, any idea where it is?

**Comment by purcell** [comment]
Can you point me at the code, or a method to reproduce? This is a little abstract, sorry. `nix-emacs-ci` enables modules explicitly.

**Comment by xuchunyang** [comment]
Create a module, e.g.,

```c
// test.c
#include <emacs-module.h>
int plugin_is_GPL_compatible;
```

And build it on github action with

    cc -shared -fpic test.c -o test.so

Here is my attempt which fails
- https://github.com/xuchunyang/strptime.el/runs/550540935?check_suite_focus=true#step:4:10

- https://github.com/xuchunyang/strptime.el/blob/d56fb734bb60dee52f638f3740e4b32ea89e0e58/.github/workflows/test.yml

**Comment by purcell** [comment]
Right, thanks. Well, that's a question of which `cc` you have, and where it looks for headers: nix will have installed Emacs and its headers into the nix store, not any standard location where `cc` would look. I'd probably just write a little nix derivation to build the module via Nix: it would require the corresponding `emacs` attribute as a `buildInput`.

Alternatively, if you're using a system CC, you can probably find the corresponding `emacs` in the nix store and add its headers directory to the CC command line with `-I`.

**Comment by purcell** [comment]
Okay...

So, this method works by installing emacs into the user's nix profile, which means that the emacs headers will be available in `~/.nix-profile/include`.

Specifically, you should find that the file `~/.nix-profile/include/emacs-module.h` is present.

**Comment by xuchunyang** [comment]
I tried to run  `find / -type f -name emacs-module.h` on github action but couldn't find the header file.

> this method works by installing emacs into the user's nix profile

Not sure how to do this, I have zero knowledge of nix.

**Comment by purcell** [comment]
Give it a try with `-I$HOME/.nix-profile/include`.

**Comment by xuchunyang** [comment]
Thanks. It works for snapshot, though 26 does not.

**Comment by purcell** [comment]
Interesting. I'm not sure I quite understand what the bug is. I checked with Emacs 26.3 locally and `emacs-module.h` was present, but I'm not sure which `make install` you're talking about - do you mean the one for the module, or for Emacs itself.

**Comment by xuchunyang** [comment]
Something installs `emacs-module.h` to `$HOME/.nix-profile/include` for the snapshot Emacs, I guess that's `make install`.

**Comment by purcell** [comment]
Yeah, under the covers it is calling `make install` (though with Nix it's a bit more complicated!).

I installed Emacs 26.3 using this method (`nix-emacs-ci`, as used by the `setup-emacs` action) and that `.h` file was present, so I'm surprised if you're only seeing that file with the snapshot build.

**Comment by xuchunyang** [comment]
> I installed Emacs 26.3 using this method (`nix-emacs-ci`, as used by the `setup-emacs` action) and that `.h` file was present

Was (and where) the .h file installed? It is not in $HOME/.nix-profile/include, otherwise the github action won't complain that it can't find the .h file.

**Comment by purcell** [comment]
At least on my machine, installing Emacs 26.3 put the `.h` file in `~/.nix-profile/include`. I'm on a Mac and haven't tested elsewhere.

**Comment by xuchunyang** [comment]
OK, 26.3 is also good, I re-run my github action and find out both 26.3 and snapshot are successful. I didn't realize 26.3 is OK because github cancels the 26.3 build once it notices another build (that's 26.1) fails.

**Comment by purcell** [comment]
Ah, that makes sense. I've added a link to your project from the README here, in case it helps other people.
